const translations = {
  address: 'address',
  addToCart: 'Add to Cart',
  appLatest: 'Orema Latest Products',
  appName: 'OremaShop',
  button: 'button',
  cart: 'Cart',
  city: 'City',
  confirmPassword: 'Confirm password',
  continue: 'Continue',
  country: 'Country',
  description: 'Description',
  details: 'Details',
  email: 'Email',
  emailAddress: 'Email Address',
  emptyCart: 'Your cart is empty',
  enterAddress: 'Enter your address',
  enterCity: 'Enter your city name',
  enterConfirmPassword: 'Enter your password again',
  enterCountry: 'Enter your country name',
  enterEmail: 'Enter your email',
  enterName: 'Enter your name',
  enterPassword: 'Enter your password',
  enterPhoneNumber: 'Enter your phone number :ex: +900000000...',
  enterPostalCode: 'Enter Postal Code',
  enterImageUrl: '/images/akim.jpg',
  file: 'file',
  goBack: 'Go Back',
  haveAnAcoount: 'Have and Account?',
  inStock: 'In Stock',
  items: 'items',
  livingAddress: 'Living address',
  loading: 'Loading...',
  login: 'Login',
  logout: 'Logout',
  markAsDelivered: 'Mark As Delivered',
  method: 'Method',
  myPicture: 'My Picture',
  myOrders: 'My Orders',
  name: 'name',
  newCustomer: 'New Customer?',
  orderItems: 'Order Items',
  order: 'Order',
  orderSummary: 'Order Summary',
  outOfStock: 'Out of Stock',
  password: 'password',
  paypal: 'PayPal',
  payment: 'Payment',
  paymentMethod: 'Payment Method',
  phoneNumer: 'Phone number',
  placeOrder: 'Place Order',
  postalCode: 'Postal Code',
  price: 'Price',
  primary: 'Primary',
  proceedToCheckout: 'Proceed to Checkout',
  profile: 'Profile',
  profileUpdated: 'Profile Updated',
  qty: 'Qty',
  radio: 'radio',
  register: 'Register',
  search: 'Search',
  searchProducts: 'Search Products...',
  selectMethod: 'Select Method',
  shipping: 'Shipping',
  shoppingCart: 'Shopping Cart',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  status: 'Status',
  submit: 'Submit',
  subtotal: 'Subtotal',
  tax: 'Tax',
  text: 'text',
  tl: '₺',
  total: 'Total',
  update: 'Update',
  userImage: 'User Image',
  username: 'username',
  userProfile: 'User Profile',
};

export default translations;
