const translations = {
  address: 'Living address',
  addToCart: 'Add to Cart',
  appLatest: 'Orema Latest Products',
  appName: 'OremaShop',
  cart: 'Cart',
  confirmPassord: 'Confirm passwowd',
  description: 'Description',
  email: 'Email',
  emailAddress: 'Email Address',
  emptyCart: 'Your cart is empty',
  enterAddress: 'Enter your address',
  enterConfirmPassword: 'Enter your password again',
  enterEmail: 'Enter your email',
  enterName: 'Enter your name',
  enterPassword: 'Enter your password',
  enterPhoneNumber: 'Enter your phone number :ex: +900000000...',
  goBack: 'Go Back',
  haveAnAcoount: 'Have and Account?',
  inStock: 'In Stock',
  items: 'items',
  loading: 'Loading...',
  login: 'Login',
  logout: 'Logout',
  myPicture: 'My Picture',
  myOrders: 'My Orders',
  name: 'name',
  newCustomer: 'New Customer?',
  outOfStock: 'Out of Stock',
  password: 'password',
  phoneNumer: 'Phone number',
  price: 'Price',
  proceedToCheckout: 'Proceed to Checkout',
  profile: 'Profile',
  qty: 'Qty',
  register: 'Register',
  search: 'Search',
  searchProducts: 'Search Products...',
  shoppingCart: 'Shopping Cart',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  status: 'Status',
  subtotal: 'Subtotal',
  text: 'text',
  tl: '₺',
  update: 'Update',
  username: 'username',
  userProfile: 'User Profile',
};

export default translations;
