const CONS = {
  STR_ADMIN: 'admin',
  STR_ADMINMENU: 'adminmenu',
  STR_API: 'api',
  STR_AUTH: 'auth',
  STR_CART: 'cart',
  STR_CONS: ':',
  STR_EDIT: 'edit',
  STR_EQ: '=',
  STR_FORWARDSLASH: '/',
  STR_ID: 'id',
  STR_INPUT_STRING: 'Your input should be a valid string',
  STR_LOGIN: 'login',
  STR_LOGOUT: 'logout',
  STR_ME: 'me',
  STR_MYORDER: 'myorder',
  STR_MYORDERS: 'myorders',
  STR_ORDER: 'order',
  STR_ORDERLIST: 'orderlist',
  STR_ORDERS: 'orders',
  STR_PAGE: 'page',
  STR_PAY: 'pay',
  STR_PAYMENT: 'payment',
  STR_PAYMENTMETHOD: 'paymentMethod',
  STR_PAYMENTS: 'payments',
  STR_PLACEORDER: 'placeorder',
  STR_PRODUCTLIST: 'productlist',
  STR_PRODUCT: 'product',
  STR_PRODUCTS: 'products',
  STR_PROFILE: 'profile',
  STR_QM: '?',
  STR_QTY: 'qty',
  STR_REDIRECT: 'redirect',
  STR_REGISTER: 'register',
  STR_REVIEW: 'review',
  STR_REVIEWS: 'reviews',
  STR_SHIPPING: 'shipping',
  STR_SHIPPING_ADDRESS: 'shippingAddress',
  STR_SEARCH: 'search',
  STR_TOP: 'top',
  STR_UPDATEDETAILS: 'updatedetails',
  STR_USER: 'user',
  STR_USERLIST: 'userlist',
  STR_USERS: 'users',
};

export default CONS;
