const TYPES = {
  CAI: 'CART_ADD_ITEM',
  CRI: 'CART_REMOVE_ITEM',
  PLF: 'PRODUCT_LIST_FAIL',
  PLR: 'PRODUCT_LIST_REQUEST',
  PLS: 'PRODUCT_LIST_SUCCESS',
  PDF: 'PRODUCT_DETAILS_FAIL',
  PDR: 'PRODUCT_DETAILS_REQUEST',
  PDS: 'PRODUCT_DETAILS_SUCCESS',
  UDF: 'USER_DETAILS_FAIL',
  UDR: 'USER_DETAILS_REQUEST',
  UDS: 'USER_DETAILS_SUCESS',
  ULF: 'USER_LOGIN_FAIL',
  ULR: 'USER_LOGIN_REQUEST',
  ULS: 'USER_LOGIN_SUCESS',
  URF: 'USER_REGISTER_FAIL',
  URR: 'USER_REGISTER_REQUEST',
  URS: 'USER_REGISTER_SUCESS',
  ULT: 'USER_LOGOUT',
};

export default TYPES;
